# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"example_function": "00_core.ipynb",
         "example_function2": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://johnowhitaker.github.io/ds_zero/"

git_url = "https://github.com/johnowhitaker/ds_zero/tree/master/"

def custom_doc_links(name): return None
