# AUTOGENERATED! DO NOT EDIT! File to edit: 00_core.ipynb (unless otherwise specified).

__all__ = ['example_function', 'example_function2']

# Cell
def example_function(a):
    return a+5

# Cell
def example_function2(a):
    return a+2